// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("address_status")]
public partial class AddressStatus
{
    [Key]
    [Column("status_id")]
    public int StatusId { get; set; }

    [Column("address_status")]
    [StringLength(255)]
    [Unicode(false)]
    public string AddressStatus1 { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; } = new List<CustomerAddress>();
}