// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("book_language")]
public partial class BookLanguage
{
    [Key]
    [Column("language_id")]
    public int LanguageId { get; set; }

    [Column("language_code")]
    [StringLength(10)]
    [Unicode(false)]
    public string LanguageCode { get; set; }

    [Column("language_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string LanguageName { get; set; }

    [InverseProperty("Language")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}