// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("book")]
public partial class Book
{
    [Key]
    [Column("book_id")]
    public int BookId { get; set; }

    [Column("title")]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("isbn13")]
    [StringLength(13)]
    [Unicode(false)]
    public string Isbn13 { get; set; }

    [Column("language_id")]
    public int? LanguageId { get; set; }

    [Column("num_pages")]
    public int? NumPages { get; set; }

    [Column("publication_date")]
    public DateOnly? PublicationDate { get; set; }

    [Column("publisher_id")]
    public int? PublisherId { get; set; }

    [ForeignKey("LanguageId")]
    [InverseProperty("Books")]
    public virtual BookLanguage Language { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    [ForeignKey("PublisherId")]
    [InverseProperty("Books")]
    public virtual Publisher Publisher { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("Books")]
    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();
}