// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

public partial class BookStoreDBContext : DbContext
{
    public BookStoreDBContext(DbContextOptions<BookStoreDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<AddressStatus> AddressStatuses { get; set; }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookLanguage> BookLanguages { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<CustOrder> CustOrders { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<OrderHistory> OrderHistories { get; set; }

    public virtual DbSet<OrderLine> OrderLines { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<Publisher> Publishers { get; set; }

    public virtual DbSet<ShippingMethod> ShippingMethods { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK__address__CAA247C84DB6E161");

            entity.Property(e => e.AddressId).ValueGeneratedNever();

            entity.HasOne(d => d.Country).WithMany(p => p.Addresses).HasConstraintName("FK__address__country__46E78A0C");
        });

        modelBuilder.Entity<AddressStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__address___3683B531C82B49E4");

            entity.Property(e => e.StatusId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Author>(entity =>
        {
            entity.HasKey(e => e.AuthorId).HasName("PK__author__86516BCFB3B97EA8");

            entity.Property(e => e.AuthorId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.BookId).HasName("PK__book__490D1AE1C6CAC6AB");

            entity.Property(e => e.BookId).ValueGeneratedNever();

            entity.HasOne(d => d.Language).WithMany(p => p.Books).HasConstraintName("FK__book__language_i__3D5E1FD2");

            entity.HasOne(d => d.Publisher).WithMany(p => p.Books).HasConstraintName("FK__book__publisher___3E52440B");

            entity.HasMany(d => d.Authors).WithMany(p => p.Books)
                .UsingEntity<Dictionary<string, object>>(
                    "BookAuthor",
                    r => r.HasOne<Author>().WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__book_auth__autho__4222D4EF"),
                    l => l.HasOne<Book>().WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__book_auth__book___412EB0B6"),
                    j =>
                    {
                        j.HasKey("BookId", "AuthorId").HasName("PK__book_aut__A1680C5DB36FEB0D");
                        j.ToTable("book_author");
                        j.IndexerProperty<int>("BookId").HasColumnName("book_id");
                        j.IndexerProperty<int>("AuthorId").HasColumnName("author_id");
                    });
        });

        modelBuilder.Entity<BookLanguage>(entity =>
        {
            entity.HasKey(e => e.LanguageId).HasName("PK__book_lan__804CF6B3C843E5F4");

            entity.Property(e => e.LanguageId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.CountryId).HasName("PK__country__7E8CD055F1D7B5C2");

            entity.Property(e => e.CountryId).ValueGeneratedNever();
        });

        modelBuilder.Entity<CustOrder>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__cust_ord__46596229964BCE6F");

            entity.Property(e => e.OrderId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.CustOrders).HasConstraintName("FK__cust_orde__custo__5441852A");

            entity.HasOne(d => d.DestAddress).WithMany(p => p.CustOrders).HasConstraintName("FK__cust_orde__dest___5629CD9C");

            entity.HasOne(d => d.ShippingMethod).WithMany(p => p.CustOrders).HasConstraintName("FK__cust_orde__shipp__5535A963");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__customer__CD65CB85356E3811");

            entity.Property(e => e.CustomerId).ValueGeneratedNever();
        });

        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.HasKey(e => new { e.CustomerId, e.AddressId }).HasName("PK__customer__51CFEFF9149F181F");

            entity.HasOne(d => d.Address).WithMany(p => p.CustomerAddresses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__customer___addre__4E88ABD4");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerAddresses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__customer___custo__4D94879B");

            entity.HasOne(d => d.Status).WithMany(p => p.CustomerAddresses).HasConstraintName("FK__customer___statu__4F7CD00D");
        });

        modelBuilder.Entity<OrderHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__order_hi__096AA2E914B70F8F");

            entity.Property(e => e.HistoryId).ValueGeneratedNever();

            entity.HasOne(d => d.Order).WithMany(p => p.OrderHistories).HasConstraintName("FK__order_his__order__5EBF139D");

            entity.HasOne(d => d.Status).WithMany(p => p.OrderHistories).HasConstraintName("FK__order_his__statu__5FB337D6");
        });

        modelBuilder.Entity<OrderLine>(entity =>
        {
            entity.HasKey(e => e.LineId).HasName("PK__order_li__F5AE5F62E77610BE");

            entity.Property(e => e.LineId).ValueGeneratedNever();

            entity.HasOne(d => d.Book).WithMany(p => p.OrderLines).HasConstraintName("FK__order_lin__book___59FA5E80");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderLines).HasConstraintName("FK__order_lin__order__59063A47");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__order_st__3683B531C6F0E32D");

            entity.Property(e => e.StatusId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Publisher>(entity =>
        {
            entity.HasKey(e => e.PublisherId).HasName("PK__publishe__3263F29D5CD8EB3A");

            entity.Property(e => e.PublisherId).ValueGeneratedNever();
        });

        modelBuilder.Entity<ShippingMethod>(entity =>
        {
            entity.HasKey(e => e.MethodId).HasName("PK__shipping__747727B66CC002EB");

            entity.Property(e => e.MethodId).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}