// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("cust_order")]
public partial class CustOrder
{
    [Key]
    [Column("order_id")]
    public int OrderId { get; set; }

    [Column("order_date", TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }

    [Column("customer_id")]
    public int? CustomerId { get; set; }

    [Column("shipping_method_id")]
    public int? ShippingMethodId { get; set; }

    [Column("dest_address_id")]
    public int? DestAddressId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustOrders")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("DestAddressId")]
    [InverseProperty("CustOrders")]
    public virtual Address DestAddress { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderHistory> OrderHistories { get; set; } = new List<OrderHistory>();

    [InverseProperty("Order")]
    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    [ForeignKey("ShippingMethodId")]
    [InverseProperty("CustOrders")]
    public virtual ShippingMethod ShippingMethod { get; set; }
}