// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[PrimaryKey("CustomerId", "AddressId")]
[Table("customer_address")]
public partial class CustomerAddress
{
    [Key]
    [Column("customer_id")]
    public int CustomerId { get; set; }

    [Key]
    [Column("address_id")]
    public int AddressId { get; set; }

    [Column("status_id")]
    public int? StatusId { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("CustomerAddresses")]
    public virtual Address Address { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomerAddresses")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("CustomerAddresses")]
    public virtual AddressStatus Status { get; set; }
}