// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("order_line")]
public partial class OrderLine
{
    [Key]
    [Column("line_id")]
    public int LineId { get; set; }

    [Column("order_id")]
    public int? OrderId { get; set; }

    [Column("book_id")]
    public int? BookId { get; set; }

    [Column("price")]
    public int? Price { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("OrderLines")]
    public virtual Book Book { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderLines")]
    public virtual CustOrder Order { get; set; }
}