// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("order_history")]
public partial class OrderHistory
{
    [Key]
    [Column("history_id")]
    public int HistoryId { get; set; }

    [Column("order_id")]
    public int? OrderId { get; set; }

    [Column("status_id")]
    public int? StatusId { get; set; }

    [Column("status_date")]
    public DateOnly? StatusDate { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderHistories")]
    public virtual CustOrder Order { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("OrderHistories")]
    public virtual OrderStatus Status { get; set; }
}