// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("order_status")]
public partial class OrderStatus
{
    [Key]
    [Column("status_id")]
    public int StatusId { get; set; }

    [Column("status_value")]
    [StringLength(255)]
    [Unicode(false)]
    public string StatusValue { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<OrderHistory> OrderHistories { get; set; } = new List<OrderHistory>();
}