// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BusinessObjects.Models;

[Table("publisher")]
public partial class Publisher
{
    [Key]
    [Column("publisher_id")]
    public int PublisherId { get; set; }

    [Column("publisher_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string PublisherName { get; set; }

    [InverseProperty("Publisher")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}